### ISSUE TITLE
Unhandled rejection SequelizeConnectionRefusedError

### ISSUE THREAD

**Issue by xavierleonardo** [MarcosRenato266/Grow-Roadmaps#17]
Pessoal, levantei um PostgreSQL no Docker com o `docker-compose` para rodar a aplicação mas não tenho muita experiência com isso e estou recebendo o seguinte erro de conexão ao iniciar a api:

```shell
== Grow Roadmaps Starting ==
Unhandled rejection SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432
    at connection.connect.err (/home/xavier/Desktop/Grow-Roadmaps/api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:116:24)                                             
    at Connection.connectingErrorHandler (/home/xavier/Desktop/Grow-Roadmaps/api/node_modules/pg/lib/client.js:163:14)                                                                       
    at Connection.emit (events.js:189:13)                                                                                                                                                    
    at Connection.EventEmitter.emit (domain.js:441:20)                                                                                                                                       
    at Socket.reportStreamError (/home/xavier/Desktop/Grow-Roadmaps/api/node_modules/pg/lib/connection.js:71:10)                                                                             
    at Socket.emit (events.js:189:13)                                                                                                                                                        
    at Socket.EventEmitter.emit (domain.js:441:20)                                                                                                                                           
    at emitErrorNT (internal/streams/destroy.js:82:8)                                                                                                                                        
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)                                                                                                                                
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
Meu `docker-compose.yml` está assim:
```yml
# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ***
```

E meu `.env` assim:
```env
SESSION_SECRET=******

DEV_DB_USERNAME=postgres
DEV_DB_PASSWORD=***
DEV_DB_NAME=grow_roadmaps
DEV_DB_HOSTNAME=localhost

# Not required for development
PROD_DB_USERNAME=<db user>
PROD_DB_PASSWORD=<db pass>
PROD_DB_NAME=grow_roadmaps
PROD_DB_HOSTNAME=localhost
```
Alguém sabe o que estou perdendo aqui?

**Comment by MarcosRenato266** [comment]
Xavier tenta setar a porta para a default do postgres 5432. Ja aconteceu comigo de o postgree estar na 5433 e dar esse problema. Voce pode configurar tbm para request local no postgres ser "trust" caso o problema seja no email. Um ultimo ponto e que se tua senha tiver caracter especial as vezes da xabu ja aconteceu cmg tbm rsrsrsrs

**Comment by xavierleonardo** [comment]
Não sei exatamente o que houve de errado mas parece que agora consegui rodar.

Eu removi as imagens que já haviam sido instaladas em minha máquina e a única coisa que mudei no meu arquivo de configuração foi setar a chave `volumes`.

Apartir daí segui os seguintes passos:

- `docker-compose up --force-recreate
- Acessei o container e criei o banco `grow_roadmaps`
- `yarn dev`

E assim obtive os logs:

![image](https://user-images.githubusercontent.com/24261979/56867958-88ba6680-69c2-11e9-9282-b1e4c3618344.png)

Muito obrigado pela ajuda @MarcosRenato266
